<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Length
    |--------------------------------------------------------------------------
    |
    | This value is the length of the OTP (One Time Password) that will be
    | generated by the application. You can adjust this value to change the
    | length of the OTP as per your requirements.
    |
    */
    
    'length' => 6,
];